source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target "kr" do
    pod 'Alamofire', '~> 3.0'
    pod 'SnapKit', '~> 0.0'
    pod 'DKChainableAnimationKit', '~> 1.0'
    pod 'EasyAnimation', '~> 1.0'
    pod 'YapDatabaseExtensions'
end